### ISSUE TITLE
see #70 AttributeError

### ISSUE THREAD

**Issue by Z-2148** [SHI-Labs/NATTEN#71] opened 2023-12-06 11:08 UTC
Hello. 
I installed natten using this pip command, but still have this error.

pip3 install natten -f https://shi-labs.com/natten/wheels/cu118/torch2.0.0/index.html

AttributeError: module 'natten._C' has no attribute 'na2d_qk_forward'

**Comment by alihassanijr** [comment] 2023-12-06 13:38
Duplicate of #70 .

**Closed by alihassanijr** 2023-12-06 13:38 UTC
