### ISSUE TITLE
NeighborhoodAttention3D

### ISSUE THREAD

**Issue by glq-1992** [SHI-Labs/NATTEN#65] opened 2023-11-12 11:30 UTC
When I use the NeighborhoodAttention3D class, the error is reported as following "AttributeError: module 'natten._C' has no attribute 'na3d_qk_forward'". I have installed natten, but there was no "na3d_qk_forward" in the _C.py file.

**Comment by naumanbashir70** [comment] 2023-11-25 21:18
@glq-1992 I have encountered the same error. Were you successful in resolving the issue?

**Comment by alihassanijr** [comment] 2023-11-26 00:50
Thank you for your interest. I think the issue is that you've only cloned the project or installed the python package without the C library. The python package is just an interface, all neighborhood attention ops are written in C++ / CUDA, and built into a library that the python package gets binded to.

Can you please confirm you built from source successfully, or installed NATTEN through our website?

**Comment by naumanbashir70** [comment] 2023-11-30 21:15
Hi,

I installed it using the command "pip3 install natten -f https://shi-labs.com/natten/wheels/cu118/torch2.0.0/index.html".

It works for 1D and 2D, but not for 3D.

I attempted to install it from the source, but the setup consistently failed. I tried both on COLAB and my local server.

`Obtaining file:///content/NATTEN
  Preparing metadata (setup.py) ... done
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from natten==0.14.7.dev0) (23.2)
Installing collected packages: natten
  Attempting uninstall: natten
    Found existing installation: natten 0.14.6+torch200cu118
    Uninstalling natten-0.14.6+torch200cu118:
      Successfully uninstalled natten-0.14.6+torch200cu118
  Running setup.py develop for natten
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of natten
  Moving to /usr/local/lib/python3.10/dist-packages/natten-0.14.6+torch200cu118.dist-info/
   from /usr/local/lib/python3.10/dist-packages/~atten-0.14.6+torch200cu118.dist-info
  Moving to /usr/local/lib/python3.10/dist-packages/natten/
   from /usr/local/lib/python3.10/dist-packages/~atten
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by naumanbashir70** [comment] 2023-12-05 22:34
@alihassanijr thank you!

I encountered an issue while attempting to install Natten from the source using `pip install -e .`. The setup does not complete successfully.

When trying to install using either of the following commands:
`pip3 install natten -f https://shi-labs.com/natten/wheels/cu118/torch2.0.0/index.html`
or 
`pip3 install natten`

I observed that the natten3d.py file is missing in the lib/site-packages/ directory.

To address this, I manually added the natten3d.py file and the corresponding 3D method in functional.py. However, this resulted in an error: "AttributeError: module 'natten._C' has no attribute 'na3d_qk_forward'", even though Natten was installed. I verified that there was no "na3d_qk_forward" in the _C.py file.

Please let me know if I am missing any steps.

**Comment by alihassanijr** [comment] 2023-12-06 17:24
Yes, you're not supposed to copy over the python files, because those are just the interface, and not the implementation.

But thanks for bringing this up, I had completely forgotten that NA3D was not in any of our stable releases.

If you are interested in it, you have to build from source.
If it fails, please share the log file (make sure to use the Makefile so that it pipes everything into a file) and I'd be happy to help figure it out.

**Comment by naumanbashir70** [comment] 2023-12-07 18:14
@alihassanijr, thank you for the suggestions, it worked.

**Comment by alihassanijr** [comment] 2023-12-28 22:50
Closing this due to inactivity; feel free to reopen if anything else.

**Closed by alihassanijr** 2023-12-28 22:50 UTC

**Comment by naumanbashir70** [comment] 2024-02-06 17:05
After the recent update, I am experiencing the following issues when installing the new packages.

`!pip3 install natten==0.15.1+torch200cu117 -f https://shi-labs.com/natten/wheels`

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/natten/functional.py](https://localhost:8080/#) in <module>
     31 try:
---> 32     from natten import libnatten  # type: ignore
     33 except ImportError:

ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
2 frames
[/usr/local/lib/python3.10/dist-packages/natten/functional.py](https://localhost:8080/#) in <module>
     32     from natten import libnatten  # type: ignore
     33 except ImportError:
---> 34     raise ImportError(
     35         "Failed to import NATTEN's CPP backend. "
     36         "This could be due to an invalid/incomplete install. "

ImportError: Failed to import NATTEN's CPP backend. This could be due to an invalid/incomplete install. Please uninstall NATTEN (pip uninstall natten) and re-install with the correct torch build: shi-labs.com/natten .

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
--------------------------------------------------------------------------- `


and with 
`!pip3 install natten==0.15.1+torch210cu121 -f https://shi-labs.com/natten/wheels/`

`pip3 install natten==0.15.1+torch200cu118 -f https://shi-labs.com/natten/wheels install natten==0.15.1+torch210cu121 -f https://shi-labs.com/natten/wheels/
Looking in links: https://shi-labs.com/natten/wheels, https://shi-labs.com/natten/wheels/
Collecting natten==0.15.1+torch200cu118
  Downloading https://shi-labs.com/natten/wheels/cu118/torch2.0.0/natten-0.15.1%2Btorch200cu118-cp39-cp39-linux_x86_64.whl (89.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.8/89.8 MB 11.0 MB/s eta 0:00:00
Requirement already satisfied: install in /local/data0/software/miniconda3/envs/namnat/lib/python3.9/site-packages (1.3.5)
ERROR: Cannot install natten==0.15.1+torch200cu118 and natten==0.15.1+torch210cu121 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested natten==0.15.1+torch200cu118
    The user requested natten==0.15.1+torch210cu121

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
`
