### ISSUE TITLE
(0.14.6) CUDA error in `attn = attn.softmax(dim=-1)`

### ISSUE THREAD

**Issue by fabrizioguillaro** [SHI-Labs/NATTEN#41] opened 2023-08-23 09:06 UTC
Dear Natten team,
I came across a runtime issue within your code. 
While I successfully trained a neural network using your model without any problems, however at inference time an error occurs, especially with datasets containing large images.

The error is:
`RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.`

What usually happens is the following:
- the code runs smoothly for some images
- then the error [1] occurs on just the next image
- then the error [2] occurs on every subsequent image

I checked for the RAM usage of the GPU, but it does not increase with time or cause out of memory.

Error [1]:
```
File "my_test.py", line 93, in <module>
    pred = model(img)
  File "/nas/homes/user/envs/trufor_natten/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas/homes/user/algoritmi/DiNAT_seg/nat.py", line 333, in forward
    return self.forward_tokens(x)
  File "/nas/homes/user/algoritmi/DiNAT_seg/nat.py", line 320, in forward_tokens
    x, xo = level(x)
  File "/nas/homes/user/envs/trufor_natten/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas/homes/user/algoritmi/DiNAT_seg/nat.py", line 207, in forward
    x = blk(x)
  File "/nas/homes/user/envs/trufor_natten/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas/homes/user/algoritmi/DiNAT_seg/nat.py", line 145, in forward
    x = self.attn(x)
  File "/nas/homes/user/envs/trufor_natten/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas/homes/user/envs/trufor_natten/lib/python3.7/site-packages/natten/natten2d.py", line 92, in forward
    attn = attn.softmax(dim=-1)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "my_test.py", line 118, in <module>
    pred = model(img)
  File "/nas/homes/user/envs/trufor_natten/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas/homes/user/envs/trufor_natten/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/nas/homes/user/envs/trufor_natten/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nas/homes/user/envs/trufor_natten/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/nas/homes/user/envs/trufor_natten/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 444, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Error [2]
```
File "my_test.py", line 82, in <module>
    img = img.to(device)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
```

Inference piece of code where the error occurs is simply:
```with torch.no_grad():
    for index, (img, path) in enumerate(tqdm(testloader)):
          img = img.to(device)
          model.eval()
          pred = model(img)
```

natten version: `0.14.6+torch1110cu113`
pytorch version: `1.11.0`
cudatoolkit version: `1.13.1`

**Comment by alihassanijr** [comment] 2023-08-23 20:28
Thank you for your interest. The issue is likely related to indexing; larger tensors require 64-bit indexing instead of 32.
If that is the issue, this would be a duplicate of #32. Could you kindly try the temporary solution there to see if it works?
If so, I'll prepare a permanent fix in the next PR.

To clarify the temp solution, just clone my fork, and build NATTEN from source instead (assuming torch is already installed):

```
git clone https://github.com/alihassanijr/NATTEN-Torch

cd NATTEN-Torch

git checkout int64

pip3 install ninja

make
```

Once you're done, simply try running your script again and see if you face any issues.

A simpler way to evaluate is to just set up a simple script that only calls NA2D once with an input the size of your test resolution.

**Comment by verigle** [comment] 2023-09-08 13:46
> Thank you for your interest. The issue is likely related to indexing; larger tensors require 64-bit indexing instead of 32. If that is the issue, this would be a duplicate of #32. Could you kindly try the temporary solution there to see if it works? If so, I'll prepare a permanent fix in the next PR.
> 
> To clarify the temp solution, just clone my fork, and build NATTEN from source instead (assuming torch is already installed):
> 
> ```
> git clone https://github.com/alihassanijr/NATTEN-Torch
> 
> cd NATTEN-Torch
> 
> git checkout int64
> 
> pip3 install ninja
> 
> make
> ```
> 
> Once you're done, simply try running your script again and see if you face any issues.
> 
> A simpler way to evaluate is to just set up a simple script that only calls NA2D once with an input the size of your test resolution.

I install the natten from source of your fork, but also get the same error:
```bash
    x_ = self.nat(x_)
  File "/home/verigle/miniconda3/envs/lavin2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/localhost/E/projects/github/tools/NATTEN-Torch/src/natten/natten1d.py", line 88, in forward
    attn = attn.softmax(dim=-1)
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```
the pytorch vision is 2.0.1, 
cuda : 11.7

**Comment by alihassanijr** [comment] 2023-09-08 17:46
@verigle Could you please share your problem size and GPU model so I can try and replicate this on my end?

**Comment by verigle** [comment] 2023-09-09 11:59
I use GPU is 3090
I use conda create a env with command `conda create -n nat python=3.9 -y` 
then  activate env `conda activate nat`
install pytorch `conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`

**Comment by alihassanijr** [comment] 2023-09-09 17:14
Could you share your problem size? (I.e. batch size, seq_len, dim, number of attention heads, kernel size, dilation).

**Comment by verigle** [comment] 2023-09-10 02:28
batch size : 4（accumlate epoch 8）,
seq_len: 32*32+1
dim : 8
number of attention heads : 1
kernel size : 8
dilation : 1

**Comment by alihassanijr** [comment] 2023-09-10 02:32
The issue is that you're trying to use kernel size 8. Neighborhood attention is only defined for odd-sized kernels, both in order to be able to center the query pixel, and in part due to the fact that even-sized kernels would be more difficult to implement.

I am a bit surprised the api didn't catch that and return an error before even launching the kernel.
I'll keep this issue open until we add a check for that.

Switching to kernel size 9 or 7 should fix your issue.

**Comment by verigle** [comment] 2023-09-10 07:15
Switching to kernel size 9 or 7  or 3 can not  solve my issue. 
but I change pytorch vision to 1.13.1 was ok, while reinstall pytorch 2.0.1 also has problem

**Comment by alihassanijr** [comment] 2023-09-10 16:56
I'm not sure why understand what you mean by "Switching to kernel size 9 or 7 or 3 can not solve my issue."
I can tell you right away you're not supposed to use even numbers as the kernel size.
The API is supposed to catch that and throw an error because otherwise either the kernel will access out of bounds addresses and the CUDA api will throw an error, and even if that doesn't happen, the results you get are --INCORRECT--.

You should rebuild/reinstall NATTEN when you switch your PyTorch version. NATTEN is compiled with the torch C++ library and you'll likely get unexpected results if you change libtorch and not rebuild NATTEN.

**Comment by alihassanijr** [comment] 2023-09-21 01:19
Closing this now; feel free to reopen if you have more questions.

**Closed by alihassanijr** 2023-09-21 01:19 UTC
