### ISSUE TITLE
Incorporating into mainline pytorch?

### ISSUE THREAD

**Issue by jxtps** [SHI-Labs/NATTEN#149] opened 2024-07-16 22:16 UTC
Hi, excellent project, love NeighborhoodAttention2D, this should be a foundational building block in computer vision, right next to Conv2d etc. So to that end: what needs to happen to get this incorporated into mainline pytorch? 

The reason I ask is that while the project in its current form is amazing, it is very hard to use it in a production context: we develop on windows + python, train on linux + python, and deploy to linux + java/c++ ( https://github.com/bytedeco/javacpp-presets/tree/master/pytorch ), which makes incorporating a custom op like this a little tricky. 

So what do we need to do and how can I help out? 

(Don't mean to barge in, would just really like to be able to use it ;) 

CC: @zou3519

**Comment by alihassanijr** [comment] 2024-07-17 02:08
Thank you for your interest.

We agree! We think Neighborhood Attention is a powerful and flexible primitive and we'd certainly like to see it adopted in more applications. We've seen some pretty great applications of NA, but unfortunately not as wide as we had hoped.

Our understanding is that until Neighborhood Attention is used in more applications, it would be too specific a feature to request in PyTorch. We're certainly happy to help drive that integration of course, but it is not entirely up to us unfortunately.

That said, there will be challenges in doing so, given that certain design choices made in kernels that NATTEN packages may make it more challenging; our binary size and number of symbols even are too large for a package as simple as NATTEN. But those are just details.

>The reason I ask is that while the project in its current form is amazing, it is very hard to use it in a production context: we develop on windows + python, train on linux + python, and deploy to linux + java/c++ ( https://github.com/bytedeco/javacpp-presets/tree/master/pytorch ), which makes incorporating a custom op like this a little tricky.

You're very right, it is tricky to use NA without NATTEN and NATTEN is just limited to being a PyTorch extension, so frameworks that are interoperable with PyTorch, which seems to be your case, would likely run into issues using those.

If the issue is something related to NATTEN, we'd certainly love to try and help, just drop the details in an issue.

>So what do we need to do and how can I help out?
>
>(Don't mean to barge in, would just really like to be able to use it ;)

Not at all; I'm actually unsure. I'll CC @Chillee as well since other than @zou3519 he's the only one else I've been in contact with regarding NATTEN and PyTorch to see if he has any ideas?

**Comment by Chillee** [comment] 2024-07-17 22:44
@alihassanijr I would probably agree that it would be unlikely to add Natten into core (at least, yet!). I think that the new attention API we're adding should allow NATTEN to be expressed using core PyTorch ops with reasonable perf.

**Comment by alihassanijr** [comment] 2024-07-20 21:01
Thanks @Chillee -- yes exactly; For most of NATTEN's lifetime, the kernels it provided were definitely not production level, and even though that changed with CUTLASS (more FNA than implicit GEMM, but effectively both), now the challenge is like I said both in binary size (NATTEN's still stuck in the no-JIT era) and also the matter of figuring out autotuning, etc.

**Comment by alihassanijr** [comment] 2024-10-01 18:21
The issue appears to be resolved, so closing now. Feel free to reopen if you still have questions.

**Closed by alihassanijr** 2024-10-01 18:21 UTC
