### ISSUE TITLE
Issues with the docker installation

### ISSUE THREAD

**Issue by KhrulkovV** [SHI-Labs/NATTEN#108] opened 2024-03-06 10:05 UTC
Hello!

I've been trying to install natten inside docker and could not succeed so far.
Our image is based on the standard nvidia pytorch docker 23.10 (CUDA 12.2; pytorch 2.1)

The compilation finishes successfully, however there is an import error when trying to import natten
`ImportError: /tmp/NATTEN/src/natten/libnatten.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs`

Here is the full log when building docker with an additional command
`RUN cd /tmp && git clone https://github.com/SHI-Labs/NATTEN && cd NATTEN && pip install -r requirements.txt && make CMAKE_PREFIX_PATH="/usr/local/lib/python3.10/dist-packages/torch/share/cmake" WITH_CUDA=1 CUDA_ARCH="8.0;9.0" && make test`

https://pastebin.com/WH89TwwB

Could you advise how to fix this issue?

**Comment by alihassanijr** [comment] 2024-03-06 16:58
Thank you for your interest.

Please let me try and see if I can replicate it on my end.

In the meantime, if that line is exactly what your have in your Dockerfile, you should definitely remove `make test` because the CUDA runtime and drivers are not loaded when you're building your image (at least as far as I know). So it'll be pretty much impossible running the unit tests without throwing the image into a container (again as far as I know).

**Comment by alihassanijr** [comment] 2024-03-06 17:28
The issue is indeed the PyTorch build in NGC being built with the C++11 ABI flag (`-D_GLIBCXX_USE_CXX11_ABI`).

I also noticed this particular build adds PTX for all the default architectures, which it should not be doing.

I'm working on a fix for both that should be up soon. Thank you for reporting this.

**Comment by dfyz** [comment] 2024-03-06 17:35
> The issue is indeed the PyTorch build in NGC being built with the C++11 ABI flag (`-D_GLIBCXX_USE_CXX11_ABI`).

Thank you so much! By pure coincidence, we also just finished investigating this problem. We came to the same conclusion, and were about to ask why you have to do [this](https://github.com/SHI-Labs/NATTEN/blob/f986469dd1e5a9a1455ddd581539c08d8e57dfed/csrc/CMakeLists.txt#L106). It is a little unclear from the original PR that [introduced it](https://github.com/SHI-Labs/NATTEN/pull/38/files#diff-5e47d96e16b022fd7a29152104f23aaeba5e7b1cf61c37d78c589be0abfd5d10R100) why the code needs to be built with `-D_GLIBCXX_USE_CXX11_ABI=0`.

> I also noticed this particular build adds PTX for all the default architectures, which it should not be doing.

Yup, we also noticed this, it would be great if this could be fixed!

**Comment by alihassanijr** [comment] 2024-03-06 17:44
Yes you are right, it shouldn't always be set to 0 and the value should reflect that of libtorch.

As far as I know, PyTorch does not ship their linux wheels over PyPI with `-D_GLIBCXX_USE_CXX11_ABI=1` because centos7 would be incompatible (although I'm not too sure about this).

However, either building it from source (which I think is what NGC does) will default to `-D_GLIBCXX_USE_CXX11_ABI=1` or they do that on purpose.

Up until last year, we only shipped a few kernels, and relied on PyTorch's recommended way of building extensions, which sets all of these build flags correctly, but on the other hand limited our ability to scale. We decided to switch to cmake instead to be able to parallelize building the ever-increasing number of kernel template instantiations better, among other reasons.
At the time, I must have accidentally assumed that this flag is always disabled and never used, which is clearly not the case.

The additional `-gencode` flags were just being set by something the PyTorch cmake, and we weren't clearing it. Just fixed that as well. I'll start a pull request when the new build finishes.

**Comment by dfyz** [comment] 2024-03-06 18:30
> As far as I know, PyTorch does not ship their linux wheels over PyPI with -D_GLIBCXX_USE_CXX11_ABI=1 because centos7 would be incompatible (although I'm not too sure about this)

Oh, indeed:
```
>>> import torch
>>> torch.__version__
'2.2.1+cu121'
>>> torch._C._GLIBCXX_USE_CXX11_ABI
False
```

I wasn't aware they did that because we haven't used PyTorch built from wheels in a long time. It all makes perfect sense then, thanks for explaining.

> However, either building it from source (which I think is what NGC does) will default to `-D_GLIBCXX_USE_CXX11_ABI=1` or they do that on purpose.

NGC does build it from source but I don't think they do anything special to activate `-D_GLIBCXX_USE_CXX11_ABI=1`, it just has been the default for quite a while ([starting from GCC 5.1](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html), which was released in 2015). That's why I was puzzled by `-D_GLIBCXX_USE_CXX11_ABI=0` in your build files -- until you explained the motivation.

**Comment by KhrulkovV** [comment] 2024-03-07 10:32
Thanks, it works out of the box now!

**Comment by pzharrington** [comment] 2024-04-18 14:17
@alihassanijr  Is this expected to be working for newer NGC pytorch versions? I'm basing on the 24.03 NGC DGL image (which is in turn based on vanilla NGC pytorch, CUDA 12.4) and having trouble. Install command is as follows, identical to the one mentioned above:
```
RUN cd /tmp && git clone https://github.com/SHI-Labs/NATTEN && cd NATTEN && \
    pip install -r requirements.txt && \
    make CMAKE_PREFIX_PATH="/usr/local/lib/python3.10/dist-packages/torch/share/cmake" WITH_CUDA=1 CUDA_ARCH="8.0"
```

In the install log I see
```
Installing collected packages: natten
  Running setup.py develop for natten
    Running command python setup.py develop
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    Building NATTEN for CPU ONLY.
```
and indeed when running a simple test, `natten.has_cuda()` evals to `False` and I get a `NATTEN was not built with cuda:0 support.`

Am I doing something wrong here? In case it's useful, [full build log is here](https://gist.github.com/pzharrington/eb01ce6ebebb650908a986b266d721b0).

**Comment by alihassanijr** [comment] 2024-04-18 14:33
@pzharrington You should try starting a gpu container and then build. As far as I know docker images with CUDA don't expose the cuda runtime and compiler when there aren't any CUDA compatible devices available, and docker build typically doesn't expose the GPUs. 

I think if you try adding this line to your dockerfile you'll find that PyTorch will also ignore CUDA-specific symbols for that reason:

```
RUN python3 -c "import torch; print(f\"{torch.cuda.is_available()=}\")"
```

**Comment by alihassanijr** [comment] 2024-04-18 18:17
You are right; compilation should not require the runtime.
I think this is a valid issue that needs to be addressed.

I don't think anything would fail if we just let the makefile flag `WITH_CUDA` override `torch.cuda.is_available()` which is what looks for cuda runtime and drivers.

I'll confirm whether this works with NGC images and push out a fix.

But I'm glad you were able to get it to work, and thank you for your interest in our project.

**Closed** 2024-04-18 20:32 UTC
