### ISSUE TITLE
Error in PyTorch container for compiled and build version

### ISSUE THREAD

**Issue by camilo-nunez** [SHI-Labs/NATTEN#28] opened 2023-04-19 20:13 UTC
Hi,

I am using the PyTorch container from [NGC Catalog - NVIDIA](https://catalog.ngc.nvidia.com/) and got problems when I tried to use the compiled version (cu117/torch1.13) and when I compile by myself.

The container version is the 22.08. According to the [release page](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-08.html#rel_22-08), this version include CUDA 11.7.1 and PyTorch 1.13.0a0+d321be6.

I ran the the container with the command `docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --rm -it nvcr.io/nvidia/pytorch:22.08-py3`
Then I checked the version with this:
```
root@bef9234ff2a2:/workspace# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

root@bef9234ff2a2:/workspace# python3 -c "import torch; print(torch.__version__)"
1.13.0a0+d321be6
```

## Compiled version problem
I installed the compiled version without problems:
```
root@bef9234ff2a2:/workspace# pip3 install natten -f https://shi-labs.com/natten/wheels/cu117/torch1.13/index.html 
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Looking in links: https://shi-labs.com/natten/wheels/cu117/torch1.13/index.html
Collecting natten
  Downloading https://shi-labs.com/natten/wheels/cu117/torch1.13/natten-0.14.6%2Btorch1130cu117-cp38-cp38-linux_x86_64.whl (55.3 MB)
     |████████████████████████████████| 55.3 MB 861 kB/s 
Requirement already satisfied: packaging in /opt/conda/lib/python3.8/site-packages (from natten) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.8/site-packages (from packaging->natten) (3.0.9)
Installing collected packages: natten
Successfully installed natten-0.14.6+torch1130cu117
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```
Finally I imported the lib and I got an error:
```
root@bef9234ff2a2:/workspace# python3 -c "from natten import NeighborhoodAttention1D, NeighborhoodAttention2D"
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/natten/functional.py", line 28, in <module>
    from natten import _C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/natten/__init__.py", line 24, in <module>
    from .natten1d import NeighborhoodAttention1D
  File "/opt/conda/lib/python3.8/site-packages/natten/natten1d.py", line 28, in <module>
    from .functional import natten1dav, natten1dqkrpb
  File "/opt/conda/lib/python3.8/site-packages/natten/functional.py", line 30, in <module>
    raise ImportError(
ImportError: Failed to import NATTEN's CPP backend. This could be due to an invalid/incomplete install. Please uninstall NATTEN (pip uninstall natten) and re-install with the correct torch build: shi-labs.com/natten
```

## Build from source problem
In a new docker, I installed `ninja`, downloaded the official repo, and ran `pip install -e .`. However, I got this long error:
https://gist.github.com/camilo-nunez/7e36a2f612bc8028fec180bffd1a091d

What can I do :c ?

**Comment by alihassanijr** [comment] 2023-04-19 23:32
Hello and thank you for your interest, and for bringing this to our attention.

I can confirm I'm facing the same issue on our end, which is strange given that we've already used NGC containers in the past.
I already know that NGC containers ship with torch built from source, so there are some differences to be expected with official builds. 
In this case, the issue appears to be half headers not existing. We're working on a solution to this right now, and we'll update this thread once we have one.

**Comment by alihassanijr** [comment] 2023-04-20 00:23
So I think I figured it out (mostly because of a similar issue happening to me before).

## The problem (in case anyone's interested)
PyTorch defines the environment variable `TORCH_CUDA_ARCH_LIST`, which specifies which architectures to target when building extensions, because PyTorch's API is responsible for calling the nvcc compiler.

With official PyTorch builds available through PyPI and conda, this environment variable is set to a default value, which gets ignored, and as a result the compiler compiles binaries for the hardware you're currently using.

In the NGC builds however, that doesn't happen, therefore torch extensions might face issues like this, especially if they're building from source.

## Temporary solution
You can just manually set this environment variable to target only your architecture, or supported architectures.

I.e., if you're on Ampere, that's compute capability 8.X, so you would compile by running:

```
TORCH_CUDA_ARCH_LIST="8.0;8.6+PTX" make
```

Or if you're unsure and don't mind the extra compilation time, compile for the intersection of all architectures supported in your CUDA version (in this case 11.7) , and those supported by NATTEN (>= 6.0):

```
TORCH_CUDA_ARCH_LIST="6.0;6.1+PTX;7.0;7.5+PTX;8.0;8.6+PTX" make
```

Reference: Our [build script](https://github.com/SHI-Labs/NATTEN/blob/main/dev/packaging/pkg_helpers.bash#L22-L60) specifies this environment variable to compile for all supported architectures given CUDA version.

## Solution that would resolve this issue for all users

I'm unsure right now unfortunately. We don't really have any control over the environment variable, and explicitly setting it will just increase compile time for users that are not on NGC builds of PyTorch.

There definitely is a way to ensure that the prebuilt wheels don't fail -- I'm still unclear why the library link fails in NGC. 

I'd keep this issue open until we figure it out and can close it with confidence.

**Comment by camilo-nunez** [comment] 2023-04-20 02:52
The temporary solution worked for me, thanks !

**Comment by alihassanijr** [comment] 2023-09-21 20:00
I'm closing this now; it's mostly a torch/NGC issue that we're probably not going to resolve.
Specifying an arch list is something that should be done by torch or by the user.

**Closed as completed by alihassanijr** 2023-09-21 20:00 UTC
Labels: bug, enhancement, NGC
